[package]
name = "opcc"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.8.21"
eyre = "0.6"
op-alloy-protocol = "0.9.2"
clap = { version = "4.5", features = ["derive"] }
rand = "0.9"
